Fix the below error message from postgresql
ERROR:  column "groups.id" must appear in the GROUP BY clause or be used in an aggregate function at character 8
STATEMENT:  SELECT id, max_participants, count(participant_id) as actual_participants FROM "groups" left join participant_groups pg on groups.id = pg.group_id WHERE event_id = $1 AND "groups"."deleted_at" IS NULL GROUP BY "group_id"
Signed-off-by: sj <sebastianthegreatful@gmail.com>